title: "Neuroscience of Development and Brain Plasticity: Longitudin"
description: ""
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/neuroscience-of-development-and-brain-plasticity-longitudinal-dataset-ages-032"
